### PR TITLE
Adjust Gutter Background, Add Trailing Padding

### LINKED ISSUE #271: 🐞 Left half of cursor cut off when at beginning of line
### Description

When the cursor is at the beginning of the line, the left half of it is cut off by the gutter view.

### To Reproduce

1. Open file
2. Place cursor at beginning of line

### Expected Behavior

Notice the left side of the cursor is cut off making it appear thinner.

### Version Information

_No response_

### Additional Context

We might add a pixel or two of left padding to prevent this.

### Screenshots

https://github.com/user-attachments/assets/069f88ad-11cf-42ed-bec1-01ebbbe13942

### PR DESCRIPTION
**Pull request by thecoolwinter**
### Description

- Updates the gutter to consider an inset for where to draw it's background.
- Adds some padding to the trailing edge when line wrap is disabled. This is not an opened issue, but while I was adjusting padding might as well.

### Related Issues

* closes #271

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### Screenshots

New leading gutter padding, includes some spacing between where the gutter starts to overlap the text and where the gutter is spaced to.

https://github.com/user-attachments/assets/35688a7f-d157-428d-9eac-8cfb35c62a1e

<details><summary>Xcode Comparison</summary>
<p>
Xcode:

Screenshot 2024-11-07 at 9 40 22 PM

CodeEdit:

Screenshot 2024-11-07 at 9 39 34 PM

</p>
</details> 

Added some padding to the trailing edge when line wrap is disabled:

Screenshot 2024-11-07 at 10 18 00 PM

### CODE REVIEW

File: Sources/CodeEditSourceEditor/Gutter/GutterView.swift [hunk 1]
```diff
@@ -204,8 +242,9 @@ public class GutterView: NSView {
         CATransaction.begin()
         superview?.clipsToBounds = false
         superview?.layer?.masksToBounds = false
-        layer?.backgroundColor = backgroundColor?.cgColor
+//        layer?.backgroundColor = backgroundColor?.cgColor
```
Comment (FastestMolasses) [inline Sources/CodeEditSourceEditor/Gutter/GutterView.swift:245]: Is this left over or is it being kept for the future?

Comment (thecoolwinter) [reply Sources/CodeEditSourceEditor/Gutter/GutterView.swift]: No that was supposed to be removed, fixed

**Review by FastestMolasses — APPROVED** [review]

**Review by tom-ludwig — APPROVED** [review]
LGTM
