### PR TITLE
Fix Ambiguous Highlights

### LINKED ISSUE #276: 🐞 tree-sitter Returns Overlapping Highlights
### Description

tree-sitter returns lots of overlapping highlights, which need to be filtered by priority to get the 'correct' highlights for a string. The old single-highlighter system just used the last value found for a range, meaning an overlap of `0..<3=.comment, 0..<3=.spell` would just highlight as `.spell`.

### To Reproduce

N/A

### Expected Behavior

The new highlighting system uses the first found value, the tree-sitter implementation should be updated to not rely on the semantics of the highlighter system and instead return non-overlapping highlights.

### Version Information

CodeEditSourceEditor: 0.8.1

### Additional Context

- Highlights returned by `SwiftTreeSitter` are already ordered: https://github.com/ChimeHQ/SwiftTreeSitter?tab=readme-ov-file#query-conflicts

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by thecoolwinter**
### Description

Fixes some bad syntax highlighting caused by overlapping captures returned from tree-sitter. Previously the last value returned took precedence, but with the new highlighting system that's not the case. This filters highlights on duplicate ranges, and prioritizes the best capture for any range so this is no longer dependent on the highlighting system's semantics.

### Related Issues

- closes #276 

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### Screenshots

Disambiguated highlights:

Screenshot 2024-11-17 at 2 50 28 PM

Ambiguous highlights:

Screenshot 2024-11-17 at 2 52 04 PM

### CODE REVIEW

File: Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+/// and passed around, so representing them with a single integer is preferable to a string to save memory.
+///
+public enum CaptureModifier: Int8, CaseIterable, Sendable {
+    case declaration
+    case definition
+    case readonly
+    case `static`
+    case deprecated
+    case abstract
+    case async
```
Comment (austincondiff) [inline Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift:31]: Does async need to go in backticks?
```suggestion
    case `async`
```

File: Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+        self.rawValue = rawValue
+    }
+
+    public static let declaration = CaptureModifierSet(rawValue: 1 << CaptureModifier.declaration.rawValue)
+    public static let definition = CaptureModifierSet(rawValue: 1 << CaptureModifier.definition.rawValue)
+    public static let readonly = CaptureModifierSet(rawValue: 1 << CaptureModifier.readonly.rawValue)
+    public static let `static` = CaptureModifierSet(rawValue: 1 << CaptureModifier.static.rawValue)
+    public static let deprecated = CaptureModifierSet(rawValue: 1 << CaptureModifier.deprecated.rawValue)
+    public static let abstract = CaptureModifierSet(rawValue: 1 << CaptureModifier.abstract.rawValue)
+    public static let async = CaptureModifierSet(rawValue: 1 << CaptureModifier.async.rawValue)
```
Comment (austincondiff) [inline Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift:108]: Does async need to go in backticks?
```suggestion
    public static let `async` = CaptureModifierSet(rawValue: 1 << CaptureModifier.async.rawValue)
```

**Review by austincondiff — CHANGES_REQUESTED** [review]
Nice work, and very well documented! I found a few potential issues. Let me know your thoughts.

**Comment by thecoolwinter** [comment]
> Nice work, and very well documented! I found a few potential issues. Let me know your thoughts.

@austincondiff most of these changes are from #273 so I think we need to wait to review this until that is merged so the actual changes are visible here. Sorry I made it convoluted. The things you commented on are from that PR

File: Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift (hunk 1 above)
Comment (thecoolwinter) [reply Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift:31]: It doesn't need backticks to compile and I can't think of why except that `async` can only exist in function definitions, so it's different from something like `extension` or `func`

Comment (austincondiff) [reply Sources/CodeEditSourceEditor/Enums/CaptureModifier.swift:31]: Awesome, I kind of figured as much. I just wanted to throw that out there just in case.

**Comment by tom-ludwig** [comment]
Would it be better to set the #273 branch as the target and merge into it instead?

**Comment by thecoolwinter** [comment]
I think actually I'll just remake this PR entirely once #273 is merged. I'd rather not muck up that PR anymore since it's so large. Leaving this open and as a draft for now just to bookmark it.

**Comment by thecoolwinter** [comment]
Okay the changes shown here now reflect the actual diff. I'm not too worried about the messy commit history since we squash PRs anyways. Ready for review now!

**Review by austincondiff — APPROVED** [review]
Looks good!
